'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class PROYECTOEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PROYECTOEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CLIENTE() As DbSet(Of CLIENTE)
    Public Overridable Property DEPARTAMENTO() As DbSet(Of DEPARTAMENTO)
    Public Overridable Property MARCA() As DbSet(Of MARCA)
    Public Overridable Property PRENDA() As DbSet(Of PRENDA)
    Public Overridable Property PROVEEDOR() As DbSet(Of PROVEEDOR)
    Public Overridable Property TALLA() As DbSet(Of TALLA)
    Public Overridable Property VENTA() As DbSet(Of VENTA)

    Public Overridable Function EditarCliente(idCliente As Nullable(Of Integer), nombre As String, apellido As String, email As String, mensaje As ObjectParameter, resultado As ObjectParameter) As Integer
        Dim idClienteParameter As ObjectParameter = If(idCliente.HasValue, New ObjectParameter("IdCliente", idCliente), New ObjectParameter("IdCliente", GetType(Integer)))

        Dim nombreParameter As ObjectParameter = If(nombre IsNot Nothing, New ObjectParameter("Nombre", nombre), New ObjectParameter("Nombre", GetType(String)))

        Dim apellidoParameter As ObjectParameter = If(apellido IsNot Nothing, New ObjectParameter("Apellido", apellido), New ObjectParameter("Apellido", GetType(String)))

        Dim emailParameter As ObjectParameter = If(email IsNot Nothing, New ObjectParameter("Email", email), New ObjectParameter("Email", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("EditarCliente", idClienteParameter, nombreParameter, apellidoParameter, emailParameter, mensaje, resultado)
    End Function

    Public Overridable Function InsertarCliente(nombre As String, apellido As String, email As String, clave As String, mensaje As ObjectParameter, resultado As ObjectParameter) As Integer
        Dim nombreParameter As ObjectParameter = If(nombre IsNot Nothing, New ObjectParameter("Nombre", nombre), New ObjectParameter("Nombre", GetType(String)))

        Dim apellidoParameter As ObjectParameter = If(apellido IsNot Nothing, New ObjectParameter("Apellido", apellido), New ObjectParameter("Apellido", GetType(String)))

        Dim emailParameter As ObjectParameter = If(email IsNot Nothing, New ObjectParameter("Email", email), New ObjectParameter("Email", GetType(String)))

        Dim claveParameter As ObjectParameter = If(clave IsNot Nothing, New ObjectParameter("Clave", clave), New ObjectParameter("Clave", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("InsertarCliente", nombreParameter, apellidoParameter, emailParameter, claveParameter, mensaje, resultado)
    End Function

End Class
